# Generated by Django 2.0.5 on 2018-06-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20180601_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileImage',
            new_name='profilePhoto',
        ),
    ]
