# Generated by Django 2.0.5 on 2018-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20180601_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
