# Generated by Django 2.0.5 on 2018-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20180601_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
