# Generated by Django 2.0.5 on 2018-06-02 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20180602_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AddField(
            model_name='ratingdone',
            name='ratedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedUser', to='mainApp.Profile'),
        ),
        migrations.AddField(
            model_name='ratingdone',
            name='ratingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingUser', to='mainApp.Profile'),
        ),
    ]
