# Generated by Django 2.0.5 on 2018-06-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20180602_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('ratedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RatingRatedUser', to='mainApp.Profile')),
                ('ratingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RatingRatingUser', to='mainApp.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('ratingUser', 'ratedUser')},
        ),
    ]
