# Generated by Django 2.0.5 on 2018-06-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20180603_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingdone',
            name='ratedUser',
        ),
        migrations.RemoveField(
            model_name='ratingdone',
            name='ratingUser',
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratedUser', to='mainApp.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratingUser', to='mainApp.Profile'),
        ),
        migrations.DeleteModel(
            name='RatingDone',
        ),
    ]
