# Generated by Django 2.0.5 on 2018-06-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20180605_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1, null=True),
        ),
    ]
