# Generated by Django 2.0.5 on 2018-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20180606_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lookingFor',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1, null=True),
        ),
    ]
