# Generated by Django 2.0.5 on 2018-06-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_auto_20180606_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sentDate']},
        ),
    ]
