# Generated by Django 2.0.5 on 2018-06-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20180606_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
