# Generated by Django 2.0.5 on 2018-06-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20180606_2054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user2', 'user1')},
        ),
    ]
